language: rust
matrix:
  fast_finish: true
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: 1.31.0
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
  allow_failures:
  - rust: nightly
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script: ci/script.sh
